spring:
  application:
    name: 'pencaucu'

  datasource:
    url: jdbc:postgresql://sape.tplinkdns.com:9671/penca_ucu
    username: killa
    password: interchange
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
